services:
  - type: web
    name: training-management-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: node ./dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
